### PR TITLE
Pitch remodeling

### PR DESCRIPTION
**Pull request by Luminilion**

### CODE REVIEW

**Comment by Luminilion** [comment]
Include organizers side of the app

**Comment by Fnux** [comment]
> Hi, we just have one question : Have your ever felt like a complete newcomer to  
> an event you attended ? Never get that feeling again with our app. 
 
I don't like it. How about something like: *We're working on a mobile application to support 
event management, helpful for both visitors and organizers. It allows to former 
to ...* 
 
> Our app features a wide range of options starting with a nice map highlighting 
> all the relevant spots, a newsfeed to stay updated, a schedule for every 
> activity in the event, and even your schedule to not miss anything. Our app 
> also helps you keeping int touch with your friends in the place and offers an  
> Organizer side to manage all these features within the app. 

Useful, but almost feels like a bullet-point list. We should shrink the 
"visitor" part by droping the *to stay updated*, *to not miss anything* and 
friends (as a reader, I feel like you're talking to an idiot). (*a nice map [...], a 
newsfeed [...], and even your schedule [...]* => *It features a real-time 
broadcast feed from the organizers, interactive map and customizable 
schedule.*) 

*In large events, we allow you to stay connected with your friends 
using geolocalization.* 

I'd also like to emphasize on the organizer section, especially where we use
the advantages of a smartphone (to scan tickets, for example). Since editing
content on a smartphone is painful, I don't think we need to advertise it.

> Finally no fears of missing out as our app connects you to a wide range of  
> events you can discover, consult and bookmark within the app. With our app the 
> event will become your event. 

The "discover" seems off-topic, since we do not plan to work with tons of  
events. It also smell marketing and feels boring to the reader, can we drop it?

**Comment by Luminilion** [comment]
> Useful, but almost feels like a bullet-point list. We should shrink the
> "visitor" part by droping the to stay updated, to not miss anything and
> friends (as a reader, I feel like you're talking to an idiot). (a nice map [...], a
> newsfeed [...], and even your schedule [...] => It features a real-time
> broadcast feed from the organizers, interactive map and customizable
> schedule.)

I agree with you on that and I will modify this part as well because your suggestion is better.

However I am not convinced by the beginning : 

> How about something like: We're working on a mobile application to support
> event management, helpful for both visitors and organizers. It allows to former
> to ...

I think even if we are not saling our app, this pitch is not very different from listing the features if it does not stand out a bit, so maybe not such an agressive "salesman-like" beginning but I would go for something more catchy. It is not something to be read but something to be said !

> I'd also like to emphasize on the organizer section, especially where we use
> the advantages of a smartphone (to scan tickets, for example). Since editing
> content on a smartphone is painful, I don't think we need to advertise it.

I tried to do it but as we did not explicitely talk about the organizer features part I did not know what to put in it (except of course the ticket scanning but that does not make much to emphasize on).

As for the end I agree that it sounds very marketing but I didn't know how to end in something that sounded right and not just dropping it and having to say _"it's done"_.

**Comment by Fnux** [comment]
> *Our app* also offers an Organizer side to manage all these features within the app.

I still think we need to more specific on this.


> Finally no fears of missing out as *our app* connects you to a wide range of events you can discover, > consult and bookmark within the app. With *our app* the event will become **your** event.

As I mentionned above, I don't think that's what we are offering with this project and thus make little sense.

**Comment by Luminilion** [comment]
> I still think we need to more specific on this.

I can now add ticket scanning, news sharing and event info editing. Did I miss something ?

> As I mentionned above, I don't think that's what we are offering with this project and thus make little > sense.

I think we cannot ommit it otherwise it can just be an app that users configure for a single event and never see another event again. In our case, the user lands on the eventpicking page which has it face all the events every time the app is launched. I can reduce it but for coherence I think we need to keep that. What do you think ?

**Pull request closed without merging**
