### PR TITLE
Migrate Sessions to Injectable

### PR DESCRIPTION
**Pull request by zyuiop**
This makes testing them easier, as we can mock the underlying `InMemorySession` easily, without having to include some test code in the main source directory.

This PR also creates a commonTest source directory, for classes that should be both in androidTest and test (see #126?)

### CODE REVIEW

**Comment by zyuiop** [comment]
I tagged you @Fnux as it's mostly your code that is modified.

**Review by Fnux — APPROVED** [review]
Looks good. It makes sense.

**Comment by zyuiop** [comment]
Okay, I didn't see you approved the principle. I'll probably rework this during next sprint.

**Comment by Luminilion** [comment]
Do we close this PR and the branch ? @zyuiop

**Pull request closed without merging**
